# Generated by Django 3.1 on 2021-02-27 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TomatoPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('target', models.CharField(choices=[('environment', 'Environment'), ('soil', 'Soil')], max_length=20)),
                ('data', models.JSONField()),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomatoes.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField()),
                ('number_of_plants', models.IntegerField()),
                ('weight_in_ton', models.IntegerField()),
                ('tomato_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomatoes.tomatoplant')),
            ],
        ),
    ]
