# Generated by Django 3.1 on 2021-02-27 16:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.CharField(default=uuid.uuid1, max_length=20, primary_key=True, serialize=False),
        ),
    ]
