# Generated by Django 3.1 on 2021-02-27 22:57

from django.db import migrations
import json
from tomatoes.serializers import SensorDataSerializer

def populate_sensor_data(apps, schema_editor):
    files = [
        ("environment", "data/environment.1614199888.json"),
        ("soil", "data/soil.1614199888.json")
    ]

    SensorData = apps.get_model('tomatoes', 'SensorData')
    for target, filename in files:
        sensor_data = json.loads(open(filename, 'r').read()).get(target, [])
        for sensor_item in sensor_data:
            sensor_id = sensor_item["sensorId"]
            del sensor_item["sensorId"]
            serializer = SensorDataSerializer(data = {
                **sensor_item,
                "sensor_id": sensor_id,
                "target": target
            })
            serializer.is_valid(raise_exception=True)
            serializer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0002_auto_20210227_1628'),
    ]

    operations = [
        migrations.RunPython(populate_sensor_data),
    ]
