# Generated by Django 3.1 on 2021-02-27 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0004_auto_20210227_2257'),
        ('tomatoes', '0003_auto_20210227_2253'),
    ]

    operations = [
    ]
