# Generated by Django 3.1 on 2021-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0005_merge_20210227_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='number_of_plants',
        ),
        migrations.AddField(
            model_name='tomatoplant',
            name='environment_condition',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tomatoplant',
            name='harvest_per_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tomatoplant',
            name='number_of_plants',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
