# Generated by Django 3.1 on 2021-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomatoes', '0006_auto_20210304_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomatoplant',
            name='soil_condition',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
